### ISSUE TITLE
Issue installing graph-tool on python

### ISSUE THREAD

**Issue by joanna350** [solstag/graph-tool#1]
I hope this is the right place to raise this question..

Brew install seems easier, but not knowing how to link it to my conda-installed python..
followed this link-> https://gist.github.com/dlozeve/ed59bba8bc8cb9b21e2af36cc9766938

Also checked the installation instruction in the tar file of graph-tool 2.26,
but returned the following error after typing `./config`

Package 'cairo', required by 'cairomm-1.0', not found

<img width="486" alt="screen shot 2018-06-04 at 2 17 29 pm" src="https://user-images.githubusercontent.com/19216902/40899528-6ddf5bc6-6802-11e8-95bd-9fc27dc59bd4.png">

Tried:
1. adding to `.bash_profile` `PKG_CONFIG_PATH = $PKG_CONFIG_PATH:<directory under anaconda where there is cairomm>`
2. `./configure -with--CAIROMM_CFLAGS -with--CAIROMM_LIBS`

No avail. not sure I implemented alternate solutions correctly either

**Comment by solstag** [comment]
Ni! Hi joanna.
Sorry, this is only an old forgotten and soon-to-be-deleted fork on github.
The real repository and issue tracker is on graph-tool's gitlab instance.
Specifically, the right place to raise your issue is here:

https://git.skewed.de/count0/graph-tool/issues

Cheers!
